from fastapi import FastAPI, HTTPException, Security, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, Field
import google.generativeai as genai
import os
import json
import re
from datetime import datetime
from dotenv import load_dotenv
from typing import List

load_dotenv()

app = FastAPI(
    title="ANOA System API", 
    description="Backend for ANOA System Purple Team Assistant"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost", "http://127.0.0.1"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Keamanan: API Key (Simulasi)
API_KEY = os.getenv("ANOA_INTERNAL_KEY", "anoa-secret-key-123")
api_key_header = APIKeyHeader(name="X-API-KEY", auto_error=False)

async def get_api_key(api_key_header: str = Security(api_key_header)):
    if api_key_header == API_KEY:
        return api_key_header
    raise HTTPException(status_code=403, detail="Could not validate credentials")

# Konfigurasi Penyimpanan Log
LOG_FILE = os.path.join(os.path.dirname(__file__), "threat_logs.json")
MAX_INPUT_LENGTH = 5000  # Proteksi DoS/Quota

# Lobster Trap Rules - Pola Regex yang lebih kuat
LOBSTER_TRAP_PATTERNS = re.compile(
    r"(?i)(ignore|disregard|forget)\s+(all|previous|any)?\s*(instructions|prompts|directions)|"
    r"act\s+as\s+(a\s+)?(dan|jailbroken|unfiltered|expert|hacker|anarchy)|"
    r"system\s+prompt\s+reveal|\[system\]|decode.*base64|payload.*injection",
    re.IGNORECASE
)

def dpi_inspect(text: str):
    match = LOBSTER_TRAP_PATTERNS.search(text)
    if match:
        return True, match.group(0)
    return False, None

def save_log_to_file(entry: dict):
    """Menyimpan log ke file JSON secara permanen."""
    logs = []
    if os.path.exists(LOG_FILE):
        try:
            with open(LOG_FILE, "r") as f:
                logs = json.load(f)
        except (json.JSONDecodeError, FileNotFoundError):
            logs = []
    
    # Tambahkan di awal (terbaru dulu) dan batasi 50 log terakhir
    logs.insert(0, entry)
    logs = logs[:50]
    
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=4)

# Konfigurasi Gemini API Key (menggunakan Free Tier)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

class Payload(BaseModel):
    data: str = Field(..., max_length=MAX_INPUT_LENGTH)
    mode: str = "red_team" # red_team, blue_team, dll

class YamlRequest(BaseModel):
    prompt: str = Field(..., max_length=1000)

@app.get("/")
def read_root():
    return {"status": "ANOA System API is Operational", "version": "2.1.0"}

@app.get("/logs", dependencies=[Depends(get_api_key)])
def get_logs():
    """Membaca log dari file untuk ditampilkan di Dashboard."""
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            return {"logs": json.load(f)}
    return {"logs": []}

@app.post("/analyze", dependencies=[Depends(get_api_key)])
def analyze_payload(payload: Payload):
    # 1. Jalankan Lobster Trap DPI Inspection
    is_blocked, pattern = dpi_inspect(payload.data)
    
    # 2. Buat entri log
    log_entry = {
        "time": datetime.now().strftime("%H:%M:%S"),
        "type": "Prompt Injection" if is_blocked else "Normal Analysis",
        "source": "192.168.1.102",  # Simulasi Source IP
        "status": "BLOCKED" if is_blocked else "ALLOWED",
        "detail": f"Matched pattern: {pattern}" if is_blocked else "Clean"
    }
    
    # 3. Simpan secara permanen
    save_log_to_file(log_entry)

    if is_blocked:
        return {
            "result": f"🛡️ [LOBSTER TRAP] Blocked: Potential malicious pattern detected.",
            "status": "blocked"
        }

    return {
        "result": f"Payload diterima. Mode: {payload.mode}. Data: {payload.data}",
        "mode": payload.mode,
    }

@app.post("/generate-yaml", dependencies=[Depends(get_api_key)])
def generate_yaml(request: YamlRequest):
    # Stub sementara untuk mengembalikan YAML yang kompatibel dengan frontend.
    return {
        "yaml_content": (
            "# Generated YAML rules for ANOA System\n"
            "# Prompt: {prompt}\n\n"
            "rules:\n"
            "  - id: 1\n"
            "    description: Sample rule generated by ANOA\n"
            "    action: alert\n"
            "    conditions:\n"
            "      - source: any\n"
            "        destination: any\n"
        ).format(prompt=request.prompt)
    }
