from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import google.generativeai as genai
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(
    title="ANOA System API", 
    description="Backend for ANOA System Purple Team Assistant"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Konfigurasi Gemini API Key (menggunakan Free Tier)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

class Payload(BaseModel):
    data: str
    mode: str = "red_team" # red_team, blue_team, dll

class YamlRequest(BaseModel):
    prompt: str

@app.get("/")
def read_root():
    return {"status": "ANOA System Backend is running!"}

@app.post("/analyze")
def analyze_payload(payload: Payload):
    # Endpoint ini nantinya akan berinteraksi dengan Gemini 
    # melalui proxy Veea Lobster Trap.
    return {
        "result": f"Payload diterima. Mode: {payload.mode}. Data: {payload.data}",
        "mode": payload.mode,
    }

@app.post("/generate-yaml")
def generate_yaml(request: YamlRequest):
    # Stub sementara untuk mengembalikan YAML yang kompatibel dengan frontend.
    return {
        "yaml_content": (
            "# Generated YAML rules for ANOA System\n"
            "# Prompt: {prompt}\n\n"
            "rules:\n"
            "  - id: 1\n"
            "    description: Sample rule generated by ANOA\n"
            "    action: alert\n"
            "    conditions:\n"
            "      - source: any\n"
            "        destination: any\n"
        ).format(prompt=request.prompt)
    }
